name: publish package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm run build

      - name: Publish package
      # run: pnpm publish --dry-run
        run: pnpm publish --access public

      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
